### ISSUE TITLE
Prepare for npm change to _ fields

### ISSUE THREAD

**Issue by vweevers** [prebuild/prebuild-install#108]
npm will soon (TBD) no longer store [`_` fields in `package.json` files in `node_modules`](https://github.com/npm/rfcs/blob/latest/accepted/0013-no-package-json-_fields.md).

This is a problem for us:

https://github.com/prebuild/prebuild-install/blob/652f16941115d7b9aa1a0d0a27d85da21e11789f/bin.js#L53-L59

**Comment by vweevers** [comment]
@ralphtheninja @mafintosh @lovell Do you recall any other places where we rely on `_` fields?

**Comment by lovell** [comment]
Oh, that's a pretty big change. I guess we'll need to check for and read the proposed `node_modules/.arborist-resolutions.json` file instead first, but the RFC is unclear about what to do if this file is expected but not present; I've added a comment as such.

**Comment by vweevers** [comment]
I'm kinda hoping there'll be some `NPM_*` environment variable(s) we can check instead.

**Comment by vweevers** [comment]
See https://github.com/npm/rfcs/pull/51

**Comment by vweevers** [comment]
Update: https://github.com/npm/rfcs/pull/51 is superseded by https://github.com/npm/rfcs/pull/90, which introduces additional breaking changes.

**Comment by isaacs** [comment]
Just for posterity, I want to mention, the shape and filename of the fallback lockfile is still not finalized, and should really be considered an arborist-internal API surface.  (Ie, even the npm cli itself won't touch it or depend on it.)

The best approach, I think, is to ensure that scripts have what they need in the environment, so that's what we're trying to maintain in npm/rfcs#90 and friends.
