### ISSUE TITLE
Private GitHub repo

### ISSUE THREAD

**Issue by VictorLeach96** [prebuild/prebuild-install#69]
I'm trying to use prebuild install with a private GitHub repo.

Is there any way we could have a similar idea where you can add your token to .prebuildrc?

**Comment by vweevers** [comment]
I think for that to work, `prebuild-install` has to use the GitHub API (rather than the public release URL), which may involve a few roundtrips to find the right asset. Starting from:

[`GET /repos/:owner/:repo/releases/tags/:tag`](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name)

**Comment by VictorLeach96** [comment]
Yep that's how I've implemented it currently.

**Comment by vweevers** [comment]
Oh, that's great :) Is your implementation public?

**Comment by VictorLeach96** [comment]
I'll get back to you about that tomorrow.

My version is based on the following with some tweaks to use the GitHub API instead.
https://github.com/WilixLead/iohook/blob/master/install.js

**Comment by VictorLeach96** [comment]
My implementation is quite messy so I'll do a fork of this repo and do a proper version for a PR.

**Comment by VictorLeach96** [comment]
I have added #75
